bile_mo_route:
    resource: "@BileMoBundle/Resources/config/routing.yml"
    prefix:   /

bile_mo:
    resource: '@BileMoBundle/Controller/'
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

app.swagger_ui:
    path: /doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
